{{- with .Values.tektonPipelines }}
{{- range . }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argo-cd
spec:
  project: {{ $.Values.project }}
  source:
    repoURL: {{ $.Values.source.repoURL }}
    targetRevision: {{ $.Values.source.targetRevision }}
    path: {{ .name}}
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: {{ $.Values.destination.server }}
    namespace: argo-cd
  syncPolicy:
    automated:
      prune: {{ $.Values.syncPolicy.automated.prune }}
      selfHeal: {{ $.Values.syncPolicy.automated.selfHeal }}
--- 
{{- end }}
{{- end }}